name: dart_mssql
description: High Performance Microsoft SQL Server Driver for Dart (32 & 64bits)
version: 0.2.5
author: Moacir Schmidt <moacir.schmidt@gmail.com>
homepage: https://www.polygonus.com
repository: https://github.com/MoacirSchmidt/dart_mssql

environment:
  sdk: ">=2.0.0 <3.0.0" 
  
dependencies: 
  meta: ^1.1.6
  collection: ^1.14.11
  string_utils: ^0.2.0
  sql_utils: ^0.2.0
  sql_recase: ^0.2.1
  sql_result: ^0.2.2