name: dart_mssql
description: High Performance Microsoft SQL Server Driver for Dart (32 & 64bits)
version: 0.2.0
author: Moacir Schmidt <moacir.schmidt@gmail.com>
homepage: https://www.polygonus.com
repository: https://github.com/MoacirSchmidt/dart_mssql

environment:
  sdk: ">=2.0.0 <3.0.0" 
  
dependencies: 
  meta: ^1.1.6
  collection: ^1.14.11
  sql_recase:
    path: ../../shared/sql_recase
  sql_result:
    path: ../../shared/sql_result
  string_utils:
    path: ../../shared/string_utils
  sql_utils:
    path: ../../server/sql_utils

dev_dependencies:
  pedantic: ^1.0.0
